pkg - functions and their respective tests - part1
stweeks-pdx/ECE571IEEE754PointAdder pull request #15
Opened 2024-05-09 21:18 UTC by anvithashirva

- members of struct float
- functions - IsZero, IsDenorm, IsNaN, IsInf
- top module to test these functions

2024-05-09 23:38 UTC, stweeks-pdx requested changes
I think this is a good start, but we probably want to catch and report errors if functions are returning the wrong flag type for our functions

2024-05-09 23:38 UTC, stweeks-pdx commented on src/floatingpointpkg.sv
> +	return ((f.exp === '0) && (f.frac === 0));
We probably should use the tick for all expressions if that is how we are going to check.

2024-05-09 23:38 UTC, stweeks-pdx commented on src/floatingpointpkg.sv
> +	return ((f.exp === '1) && (f.frac !== '0));
For NaN the f.exp should be 255

2024-05-09 23:38 UTC, stweeks-pdx commented on src/floatingpointpkg.sv
> +	return ((f.exp === '1) && (f.frac === '0));
Same with NaN, exponent bit should be 255

2024-05-09 23:38 UTC, stweeks-pdx commented on src/floatingpointpkgtest.sv
> +	$display("IsZero = %b, IsDenorm = %b, IsNaN = %b, IsInf = %b",IsZero(float),IsDenorm(float), IsNaN(float), IsInf(float));
We probably want to do more than display here. We should be checking that the float builds the number we want (maybe use the $shortrealtobits() function) and we should also be verifying flags return what we expect, should probably try a few cases. So maybe a different set of tasks.

2024-05-10 18:03 UTC, anvithashirva commented on src/floatingpointpkg.sv
> +	return ((f.exp === '0) && (f.frac === 0));
Yes, it's a typo.

2024-05-10 18:04 UTC, anvithashirva commented on src/floatingpointpkg.sv
> +	return ((f.exp === '1) && (f.frac !== '0));
Sure. I will change it.

2024-05-10 18:04 UTC, anvithashirva commented on src/floatingpointpkg.sv
> +	return ((f.exp === '1) && (f.frac === '0));
Sure. I will change it.

2024-05-10 18:06 UTC, anvithashirva commented on src/floatingpointpkgtest.sv
> +	$display("IsZero = %b, IsDenorm = %b, IsNaN = %b, IsInf = %b",IsZero(float),IsDenorm(float), IsNaN(float), IsInf(float));
I will include tasks to verify the flags.

2024-05-10 19:37 UTC, stweeks-pdx approved these changes
LGTM

2024-05-10 19:37 UTC, merged