FFO module - insomnia draft
stweeks-pdx/ECE571IEEE754PointAdder pull request #25
Opened 2024-05-11 18:31 UTC by Hector-Cardenas

First draft of a testbench using CLZ, and an FFO module using divide and conquer

2024-05-11 20:25 UTC, stweeks-pdx commented on src/findfirstone.sv
> +function automatic bit [2:0] subFFO(input bit [3:0] subWord);
Why not convert this to a module? It is pretty simple, not sure we need a function here (plus we can write a test case for it more easily).

2024-05-11 20:25 UTC, stweeks-pdx commented on src/findfirstone.sv
> +function automatic bit [2:0] subFFO(input bit [3:0] subWord);
It also just feels a bit clunky inside the findfirstone module. Also maybe findFirstOne for the module name or ffo?

2024-05-11 20:26 UTC, stweeks-pdx commented on src/findfirstone.sv
> +parameter N = 32;
```suggestion
parameter N = 23;
```

2024-05-11 20:27 UTC, stweeks-pdx commented on src/findfirstone.sv
> +for (i = 0; i < 8; i++)
We will want to parameterize this 8, probably as a localparam derived from N

2024-05-11 20:28 UTC, stweeks-pdx commented on src/findfirstone.sv
> +		assign {subV[i], subIndex[i]} = subFFO(word[4*i+3: 4*i]);
We will want a comment here for the word indexing, not easily intuitive what is being selected.

2024-05-11 20:28 UTC, stweeks-pdx commented on src/findfirstone.sv
> +		assign {subV[i], subIndex[i]} = subFFO(word[4*i+3: 4*i]);
Might be a good spot for a macro definition, so obvious to the reader is what is going on? But a comment is more than enough

2024-05-11 20:29 UTC, stweeks-pdx commented on src/findfirstone.sv
> +FourToOneMux preIdx1(subIndex[4], subIndex[5], subIndex[6], subIndex[7], idxSelect[1], subIndex[9]);
```suggestion
FourToOneMux preIdx1(subIndex[4], subIndex[5], subIndex[6], subIndex[7], idxSelect[8], subIndex[9]);
```

2024-05-11 20:30 UTC, stweeks-pdx commented on src/findfirstone.sv
> +FourToOneMux preIdx0(subIndex[0], subIndex[1], subIndex[2], subIndex[3], idxSelect[0], subIndex[8]);
So I think I get the select, but how does the out here relate to the subIndex? Maybe that can be a separate variable to make it more clear?

2024-05-11 20:32 UTC, stweeks-pdx commented on src/findfirstone.sv
> +always_comb
I'm having a really tough time following what is going on in this block

2024-05-11 20:33 UTC, stweeks-pdx commented on src/ffotb.sv
> +FindFirstOne DUT(testVal, valid, index);
Should pass in parameterized value here

2024-05-11 20:34 UTC, stweeks-pdx commented on src/ffotb.sv
> +	if ((x & 32'hFFFF0000) == 0)
I would turn these compares into macros, but again they are hardcoded so a bit tough to tell, probably fine since 23-bits is constant

2024-05-11 20:35 UTC, stweeks-pdx commented on src/ffotb.sv
> +		x = x << 1;
Are we doing anything with these X's we shift?

2024-05-11 21:05 UTC, Hector-Cardenas commented on src/findfirstone.sv
> +function automatic bit [2:0] subFFO(input bit [3:0] subWord);
Module sounds good and should be a quick fix. ffo and ffoNibble for the 4-bit module maybe? I tend to like more desctriptive module names, but this one may be straightforward enough to get by.

2024-05-11 21:09 UTC, Hector-Cardenas commented on src/ffotb.sv
> +		x = x << 1;
Each x in an if statement is used in the conditional for the next statement. Took some time for me to parse it from the wiki, but essentially the x only gets shifted if the masked result is all zeros; it's a very concise, if somewhat difficult to read, implementation of the binary search.

2024-05-11 21:12 UTC, Hector-Cardenas commented on src/ffotb.sv
> +	if ((x & 32'hFFFF0000) == 0)
Agreed; I was somewhat torn on whether effeciency trumps paramaterization in both of these modules. Was considering some compomise where we allow parameterization for only 32-bit and 64-bit float, otherwise the process seems like it would get clunky with having to concatenate 0s on top of the input and/or determining how many subFFO modules are needed.

2024-05-11 21:13 UTC, Hector-Cardenas commented on src/findfirstone.sv
> +function automatic bit [2:0] subFFO(input bit [3:0] subWord);
Totally realized I misread your comment. FindFirstOne for larger, and findFirstOne for internal module sound good if that's what you meant.

2024-05-11 22:35 UTC, stweeks-pdx commented on doc/README.md
> +![Floating Point Adder Block Diagram](https://github.com/stweeks-pdx/ECE571IEEE754PointAdder/blob/doc/FloatingPointAdder.jpg)
I need to delete this, just needs to match the current one

2024-05-12 01:35 UTC, stweeks-pdx commented on src/findfirstone.sv
> +function automatic bit [2:0] subFFO(input bit [3:0] subWord);
I wasn't trying to direct, name it what you want :)

2024-05-13 02:14 UTC, stweeks-pdx commented on src/findfirstone.sv
> +// TODO: Hard code to 24 bits
Should remove these comments

2024-05-13 02:14 UTC, stweeks-pdx commented on src/findfirstone.sv
> +// TODO: Determine how to parameterize everything below this point
Should remove comments

2024-05-13 02:14 UTC, stweeks-pdx commented on src/findfirstone.sv
> +//logic [1:0] topNibbleIdx, botNibbleIdx;
Should remove comments

2024-05-13 02:14 UTC, stweeks-pdx commented on src/findfirstone.sv
> +// TODO: Replace multiple modules with generate when parameterizing
Should remove comments

2024-05-13 02:15 UTC, stweeks-pdx commented on src/findfirstone.sv
> +// TODO: Modify final assignments when when parameterizing
Should remove comment

2024-05-13 02:16 UTC, stweeks-pdx requested changes
I'm not sure why the changes already in main (floatingpointpkg, .gitignore, Makefile) are in this PR too. Mind rebasing with the most recent version of the main branch?

2024-05-13 02:27 UTC, stweeks-pdx commented
Can you also add your build script to the Makefile please

2024-05-13 03:55 UTC, Hector-Cardenas commented
> I'm not sure why the changes already in main (floatingpointpkg, .gitignore, Makefile) are in this PR too. Mind rebasing with the most recent version of the main branch?

Yeah, I'm not sure why either. Very likely something to do with when I rebased last, but I'll try again and push with deleted comments as well.

2024-05-14 05:56 UTC, closed without merging