Control FSM
stweeks-pdx/ECE571IEEE754PointAdder pull request #40
Opened 2024-06-10 05:20 UTC by anvithashirva

Control FSM is used to enable the modules in the data-path based on the current state of the Floating point adder circuit.

2024-06-10 05:51 UTC, stweeks-pdx commented on src/control.sv
> +	//enum {I_POS= 0,D_POS = 1,EGT_POS = 2,ELT_POS = 3,SR_POS = 4, SL_POS = 5, NS_POS = 6}StateBit;
We should remove commented out code, so we don't get confused what is what.

2024-06-10 05:52 UTC, stweeks-pdx commented on src/control.sv
> +		else if (Go)
should include an else statement:
`else Result <= Result` or should be always_latch

2024-06-10 05:54 UTC, stweeks-pdx commented
Could you also just post a drawing/diagram of the FSM into the docs for this PR? I can add it to the doc.

2024-06-10 09:28 UTC, Hector-Cardenas requested changes
First part of review; will give a second pass after some sleep. (There's particularly some stuff about the outputs relying on values from previous sections that I'm we may have a problem with)

2024-06-10 09:28 UTC, Hector-Cardenas commented on src/control.sv
> +	input [MANTISSABITS+1:0] Out,
I'm using the .name convention in the integration module; can we rename this to "roundedMant"?

2024-06-10 09:28 UTC, Hector-Cardenas commented on src/control.sv
> +	output logic SelExpMuxR, SelManMuxR,
I think these two may be redundant as we'll only either be picking post or pre-rounding values. Maybe just a single SelMuxR would work.

2024-06-10 09:28 UTC, Hector-Cardenas commented on src/control.sv
> +	output logic Result );
Result is already the name of our float output; can we rename this to "ResultReady"? (or similar)

2024-06-10 09:35 UTC, Hector-Cardenas commented on src/control.sv
> +			ShiftAmount = MBITSEN - FFOIndex;
We might have to assume that FFOIndex is no longer available when we're in this state since it's crossing over a register boundary. Don't have a solution yet but will sleep on it.

2024-06-10 09:36 UTC, Hector-Cardenas commented on src/control.sv
> +			ShiftAmount = MBITSEN - FFOIndex;
First thought that comes to mind is to also throw it into the register, and just add a second input for the "R1.Index" that will contain the held value since we only need it for one extra clock

2024-06-11 20:14 UTC, Hector-Cardenas commented on src/control.sv
> +			ShiftAmount = MBITSEN - FFOIndex;
After meeting this morning, we decided on the new name "Index" for this value that will be registered in data path

2024-06-11 23:57 UTC, Hector-Cardenas commented on src/control.sv
> +			SREn = '1; IncrEn = '1;
SREn and IncrEn are equivalent and also redundant; i.e. we only ever use both of them or neither, can remove IncrEn safely.

2024-06-11 23:57 UTC, Hector-Cardenas commented on src/control.sv
> +			SLEn = '1; DecrEn = '1;
Same as with SREn/IncrEn; can remove DecrEn as it's redundant.

2024-06-12 02:25 UTC, Hector-Cardenas commented on src/control.sv
> +	output logic [$clog2(MANTISSABITS)-1:0] ShiftRightAmount,
This actually needs to be $clog2(MANTISSABITS*2) since our maximum shift is 48 due to reusability oddness in the RightShift module

2024-06-12 11:08 UTC, Hector-Cardenas commented on src/control.sv
> +				ShiftRightAmount = ExpDiff > MANTISSABITS ? MBITSEN : ExpDiff;
We have the same issue we had with FFOIndex here, in that ExpDiff is from a previous stage. Have it renamed to just Diff in my dummy FSM at the moment.

2024-06-12 15:02 UTC, anvithashirva commented on src/control.sv
> +				ShiftRightAmount = ExpDiff > MANTISSABITS ? MBITSEN : ExpDiff;
I will use the fix we decided for FFOIndex. I will include  a new input port and call in "Diff".

2024-06-13 03:32 UTC, Hector-Cardenas commented on src/control.sv
> +	output logic Ready);
Needs to be FlagResult to reflect new externalized ff

2024-06-13 03:34 UTC, Hector-Cardenas commented on src/control.sv
> +	always_ff @ (posedge Clock)
Have now externalized this always_ff block; needs to be deleted.

2024-06-13 16:19 UTC, anvithashirva commented on src/control.sv
> +	output logic Ready);
done!

2024-06-13 16:19 UTC, anvithashirva commented on src/control.sv
> +	always_ff @ (posedge Clock)
done!

2024-06-13 21:49 UTC, closed without merging